version: '3'
services:
  api:
    build: .
    command: gin run main.go
    environment:
      ENVIRONMENT: development
    ports:
      - 3000:3000
    volumes:
      - .:/go/src/github.com/NerdsvilleCEO/go-chuck-norrisify
